// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: "postgresql://zumzam_admin:SCNK88tank33@rc1b-ktk7vobktajbv2sd.mdb.yandexcloud.net:6432/zumzam?sslmode=require",
  },
});
